=== api-evangelist/amazon-organizations/json-schema/openapi-organization-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-organizations/refs/heads/main/json-schema/openapi-organization-schema.json",
  "title": "Organization",
  "description": "Organization schema from Amazon Organizations",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "Arn": {
      "type": "string"
    },
    "FeatureSet": {
      "type": "string",
      "enum": [
        "ALL",
        "CONSOLIDATED_BILLING"
      ]
    },
    "MasterAccountArn": {
      "type": "string"
    },
    "MasterAccountId": {
      "type": "string"
    },
    "MasterAccountEmail": {
      "type": "string"
    }
  }
}

=== api-evangelist/amazon-organizations/examples/openapi-organization-example.json
{
  "Id": "resource-abc123",
  "Arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "FeatureSet": "CONSOLIDATED_BILLING",
  "MasterAccountArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "MasterAccountId": "resource-abc123",
  "MasterAccountEmail": "example-string"
}
